const SEED_REPORTS = [
  { edgeId: 'e00001', type: 'ROBO', username: 'santiago', description: 'Me robaron el celular en esta esquina a las 8pm' },
  { edgeId: 'e00015', type: 'ROBO', username: 'luisa', description: 'Dos hombres en moto arrebataron un bolso' },
  { edgeId: 'e00045', type: 'ACOSO', username: 'luisa', description: 'Me siguieron por 3 cuadras, tuve que entrar a una tienda' },
  { edgeId: 'e00067', type: 'ACOSO', username: 'luisa', description: 'Gritos y comentarios obscenos al pasar por esta calle de noche' },
  { edgeId: 'e00102', type: 'ZONA_OSCURA', username: 'sotelo', description: 'No hay faroles funcionando desde hace semanas, peligroso de noche' },
  { edgeId: 'e00103', type: 'ZONA_OSCURA', username: 'santiago', description: 'Toda esta cuadra está a oscuras, el poste está dañado' },
  { edgeId: 'e00104', type: 'ZONA_OSCURA', username: 'luisa', description: 'Zona totalmente oscura después de las 7pm, eviten pasar solos' },
  { edgeId: 'e00120', type: 'SOSPECHOSO', username: 'sotelo', description: 'Grupo de personas consumiendo sustancias en la esquina' },
  { edgeId: 'e00135', type: 'SOSPECHOSO', username: 'santiago', description: 'Persona armada merodeando la zona a las 10pm' },
  { edgeId: 'e00140', type: 'SOSPECHOSO', username: 'admin', description: 'Vehículo sospechoso estacionado por horas con vidrios polarizados' },
  { edgeId: 'e00155', type: 'ACCIDENTE', username: 'luisa', description: 'Choque entre moto y taxi en el cruce, peligroso para peatones' },
  { edgeId: 'e00170', type: 'ACCIDENTE', username: 'sotelo', description: 'Peatón atropellado por no haber semáforo peatonal' },
  { edgeId: 'e00180', type: 'ROBO', username: 'admin', description: 'Robo a mano armada en tienda de la esquina, 3 heridos' },
  { edgeId: 'e00190', type: 'ROBO', username: 'santiago', description: 'Atraco a pareja de turistas, les quitaron cámara y billetera' },
  { edgeId: 'e00200', type: 'ACOSO', username: 'luisa', description: 'Hombre ebrio persiguiendo mujeres que pasaban solas' },
  { edgeId: 'e00220', type: 'ZONA_OSCURA', username: 'sotelo', description: 'Parque completamente oscuro, ideal para que roben' },
  { edgeId: 'e00235', type: 'ROBO', username: 'santiago', description: 'Celular arrebatado mientras caminaba distraído' },
  { edgeId: 'e00250', type: 'SOSPECHOSO', username: 'luisa', description: 'Dos hombres en actitud sospechosa revisando carros estacionados' },
  { edgeId: 'e00260', type: 'ACOSO', username: 'luisa', description: 'Acoso verbal constante en esta cuadra, hombres en la esquina' },
  { edgeId: 'e00275', type: 'ZONA_OSCURA', username: 'santiago', description: 'Alumbrado público inexistente, recomendable evitar de noche' },
  { edgeId: 'e00285', type: 'ROBO', username: 'sotelo', description: 'Robo de bicicleta a mano armada, 9pm' },
  { edgeId: 'e00295', type: 'ACCIDENTE', username: 'admin', description: 'Caída de motociclista por hueco en la vía sin señalizar' },
  { edgeId: 'e00310', type: 'ROBO', username: 'santiago', description: 'Hurto a residencia, rompieron ventana del primer piso' },
  { edgeId: 'e00325', type: 'SOSPECHOSO', username: 'luisa', description: 'Vendedor ambulante agresivo, posible fachada para robar' },
  { edgeId: 'e00335', type: 'ACOSO', username: 'luisa', description: 'Taxista haciendo comentarios inapropiados a mujeres en la calle' },
  { edgeId: 'e00110', type: 'ZONA_OSCURA', username: 'admin', description: 'Callejón sin iluminación usado como atajo, muy peligroso' },
  { edgeId: 'e00118', type: 'SOSPECHOSO', username: 'sotelo', description: 'Personas desconocidas rondando el CAI, posiblemente marcando policías' },
  { edgeId: 'e00150', type: 'ROBO', username: 'admin', description: 'Robo masivo en bus de transporte público, 4 víctimas' },
  { edgeId: 'e00160', type: 'ACOSO', username: 'luisa', description: 'Fotógrafo falso tomando fotos sin consentimiento a mujeres' },
  { edgeId: 'e00175', type: 'SOSPECHOSO', username: 'santiago', description: 'Cajero automático intervenido, posible clonación de tarjetas' },
  { edgeId: 'e00185', type: 'ZONA_OSCURA', username: 'sotelo', description: 'Lote baldío sin vigilancia usado para actividades ilegales' },
  { edgeId: 'e00205', type: 'ROBO', username: 'luisa', description: 'Robo de espejos de carros estacionados en la cuadra' },
  { edgeId: 'e00215', type: 'ACCIDENTE', username: 'santiago', description: 'Atropello de ciclista por bus en cruce sin señalizar' },
  { edgeId: 'e00230', type: 'SOSPECHOSO', username: 'admin', description: 'Comercio con posible venta de artículos robados' },
  { edgeId: 'e00245', type: 'ACOSO', username: 'luisa', description: 'Grupo de hombres bloqueando el paso a mujeres, intimidante' },
  { edgeId: 'e00255', type: 'ROBO', username: 'sotelo', description: 'Hurto de pertenencias en restaurante, descuido de 2 minutos' },
  { edgeId: 'e00265', type: 'ZONA_OSCURA', username: 'santiago', description: 'Tramo de la ciclovía sin iluminación, varios accidentes reportados' },
  { edgeId: 'e00280', type: 'SOSPECHOSO', username: 'luisa', description: 'Persona siguiendo estudiantes universitarios al salir de clase' },
  { edgeId: 'e00290', type: 'ROBO', username: 'admin', description: 'Asalto a pareja de extranjeros con cuchillo, les quitaron todo' },
  { edgeId: 'e00305', type: 'ACOSO', username: 'santiago', description: 'Trabajador de construcción haciendo comentarios obscenos' },
  { edgeId: 'e00315', type: 'ACCIDENTE', username: 'sotelo', description: 'Vehículo se subió al andén por falla mecánica, peatón herido' },
  { edgeId: 'e00330', type: 'ZONA_OSCURA', username: 'admin', description: 'Sector residencial sin farolas, robos frecuentes reportados' },
  { edgeId: 'e00125', type: 'SOSPECHOSO', username: 'sotelo', description: 'Carro sin placas estacionado frente a banco, posible fuga' },
  { edgeId: 'e00145', type: 'ROBO', username: 'luisa', description: 'Arrebato de cadena de oro a señora mayor, mediodía' },
  { edgeId: 'e00165', type: 'ZONA_OSCURA', username: 'santiago', description: 'Escaleras peatonales completamente oscuras, nadie debería usarlas de noche' },
  { edgeId: 'e00210', type: 'ACOSO', username: 'admin', description: 'Vendedor de drogas ofreciendo abiertamente a estudiantes' },
  { edgeId: 'e00240', type: 'ACCIDENTE', username: 'luisa', description: 'Colisión múltiple por falta de semáforo, 3 carros involucrados' },
  { edgeId: 'e00270', type: 'SOSPECHOSO', username: 'sotelo', description: 'Indigente agresivo con arma blanca amenazando transeúntes' },
  { edgeId: 'e00300', type: 'ROBO', username: 'santiago', description: 'Robo en conjunto residencial, acceso por terraza sin seguridad' },
  { edgeId: 'e00320', type: 'ACOSO', username: 'luisa', description: 'Hombre en parque tomando fotos a niños sin permiso de padres' },
];

export default SEED_REPORTS;
